//Generated by Flashman\James Chadwick at 4/27/2015 5:57 PM

declare module PersonalDomain.Application.Blogging.Models {
	interface CommentDTO {
		Id: number;
		PostId: number;
		UserId: number;
		UserName: number;
		Content: string;
	}
	interface PostDTO {
		Id: number;
		Title: string;
		Subtitle: string;
		Content: string;
		Comments: PersonalDomain.Application.Blogging.Models.CommentDTO[];
	}
	interface PostSummaryDTO {
		Id: number;
		Title: string;
		Subtitle: string;
		Author: string;
		PostedDate: string;
	}
	interface PostSummaryCountDTO {
		Count: number;
	}
}
declare module PersonalDomain.Application.Operations.Response {
	interface OperationResponse {
		IsSuccess: boolean;
	}
}
declare module PersonalDomain.Application.Operations.Request {
	interface ByIdRequest {
		Id: number;
	}
}
