//Generated by Flashman\James Chadwick at 4/26/2015 10:59 PM

module PersonalDomain.Application.Operations {
	export class BlogService {
		
		static inject = ['$http']
        constructor(private $http: ng.IHttpService) {
        }
		
		public SaveComment: (request: PersonalDomain.Application.Blogging.Models.CommentDTO) => ng.IHttpPromise<PersonalDomain.Application.Operations.Response.OperationResponse> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/SaveComment',
				data: request
			});
		}
		
		public SavePost: (request: PersonalDomain.Application.Blogging.Models.PostDTO) => ng.IHttpPromise<PersonalDomain.Application.Operations.Response.OperationResponse> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/SavePost',
				data: request
			});
		}
		
		public GetPost: (request: PersonalDomain.Application.Operations.Request.ByIdRequest) => ng.IHttpPromise<PersonalDomain.Application.Blogging.Models.PostDTO> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/GetPost',
				data: request
			});
		}
		
		public GetPostSummariesByPage: (request: PersonalDomain.Application.Operations.Request.ByIdRequest) => ng.IHttpPromise<PersonalDomain.Application.Blogging.Models.PostSummaryDTO[]> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/GetPostSummariesByPage',
				data: request
			});
		}
		
		public GetPostSummaryCount: (request: PersonalDomain.Application.Operations.Request.ByIdRequest) => ng.IHttpPromise<PersonalDomain.Application.Blogging.Models.PostSummaryCountDTO> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/GetPostSummaryCount',
				data: request
			});
		}
		
	}
}
