//Generated by Flashman\James Chadwick at 4/27/2015 9:32 PM

module PersonalDomain.Application.Operations {
	export class BlogService {
		
		static inject = ['$http']
        constructor(private $http: ng.IHttpService) {
        }
		
		public SaveComment: (request: PersonalDomain.Application.Blogging.Models.CommentDTO) => ng.IHttpPromise<PersonalDomain.Application.Operations.Response.OperationResponse> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/SaveComment',
				data: request
			});
		}
		
		public SavePost: (request: PersonalDomain.Application.Blogging.Models.PostDTO) => ng.IHttpPromise<PersonalDomain.Application.Operations.Response.OperationResponse> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/SavePost',
				data: request
			});
		}
		
		public GetPostDetailById: (request: PersonalDomain.Application.Operations.Request.ByIdRequest) => ng.IHttpPromise<PersonalDomain.Application.Blogging.Models.PostDTO> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/GetPostDetailById',
				data: request
			});
		}
		
		public GetPostIndexByPage: (request: PersonalDomain.Application.Operations.Request.GetPostIndexByPageRequest) => ng.IHttpPromise<PersonalDomain.Application.Blogging.Models.PostIndexDTO> = (request) => {
			return this.$http({
				method: 'post',
				url: '/api/GetPostIndexByPage',
				data: request
			});
		}
		
	}
}
