//Generated by Flashman\James Chadwick at 6/27/2015 3:34 PM

import aureliaHttpClient = require("aurelia-http-client");

class BlogService {

    private _baseUrl: string = "http://blog.jamespchadwick.com";
    private _httpClient: aureliaHttpClient.HttpClient;

    constructor() {
        this._httpClient = new aureliaHttpClient.HttpClient();
        (<any>this._httpClient).configure(hc => hc.withHeader("Content-Type", "application/json;charset=UTF-8"));
    }

    public SaveComment: (jsonRequest: PersonalDomain.Application.Blogging.Models.CommentDTO) => IPromise<PersonalDomain.Application.Operations.Response.OperationResponse> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/SaveComment', jsonRequest).then((httpResponse: aureliaHttpClient.IHttpResponseMessage<string>) => {
            return JSON.parse(httpResponse.response);
        });
    }  

    public SavePost: (jsonRequest: PersonalDomain.Application.Blogging.Models.PostDTO) => IPromise<PersonalDomain.Application.Operations.Response.OperationResponse> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/SavePost', jsonRequest).then((httpResponse: aureliaHttpClient.IHttpResponseMessage<string>) => {
            return JSON.parse(httpResponse.response);
        });
    }  

    public GetAuthorById: (jsonRequest: PersonalDomain.Application.Operations.Request.ByIdRequest) => IPromise<PersonalDomain.Application.Blogging.Models.AuthorDTO> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/GetAuthorById', jsonRequest).then((httpResponse: aureliaHttpClient.IHttpResponseMessage<string>) => {
            return JSON.parse(httpResponse.response);
        });
    }  

    public GetPostDetailById: (jsonRequest: PersonalDomain.Application.Operations.Request.ByIdRequest) => IPromise<PersonalDomain.Application.Blogging.Models.PostDTO> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/GetPostDetailById', jsonRequest).then((httpResponse: aureliaHttpClient.IHttpResponseMessage<string>) => {
            return JSON.parse(httpResponse.response);
        });
    }  

    public GetPostIndexByPage: (jsonRequest: PersonalDomain.Application.Operations.Request.GetPostIndexByPageRequest) => IPromise<PersonalDomain.Application.Blogging.Models.PostIndexDTO> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/GetPostIndexByPage', jsonRequest).then((httpResponse: aureliaHttpClient.IHttpResponseMessage<string>) => {
            return JSON.parse(httpResponse.response);
        });
    }  
		
}
export = BlogService;
