//Generated by Flashman\James Chadwick at 9/27/2015 9:14 PM
import {HttpClient} from 'aurelia-http-client';
import {CoreDataService} from 'core/data-service';

export class BlogDataService extends CoreDataService {
	static inject = [HttpClient];
    constructor(_httpClient: HttpClient) {
        super("http://blog.jamespchadwick.com", _httpClient);
    }
    
    public GetPostById(jsonRequest: PersonalDomain.Application.Operations.Request.ByIdRequest): Promise<PersonalDomain.Application.Blogging.Models.PostDTO> {
        return this.Post('/api/GetPostById', jsonRequest);
    }    
    
    public SaveComment(jsonRequest: PersonalDomain.Application.Blogging.Models.CommentDTO): Promise<PersonalDomain.Application.Operations.Response.OperationResponse> {
        return this.Post('/api/SaveComment', jsonRequest);
    }    
    
    public SavePost(jsonRequest: PersonalDomain.Application.Blogging.Models.PostDTO): Promise<PersonalDomain.Application.Operations.Response.OperationResponse> {
        return this.Post('/api/SavePost', jsonRequest);
    }    
    
    public GetAuthorById(jsonRequest: PersonalDomain.Application.Operations.Request.ByIdRequest): Promise<PersonalDomain.Application.Blogging.Models.AuthorDTO> {
        return this.Post('/api/GetAuthorById', jsonRequest);
    }    
    
    public GetPostBySlug(jsonRequest: PersonalDomain.Application.Operations.Request.GetPostDetailBySlugRequest): Promise<PersonalDomain.Application.Blogging.Models.PostDTO> {
        return this.Post('/api/GetPostBySlug', jsonRequest);
    }    
    
    public GetPostIndexByPage(jsonRequest: PersonalDomain.Application.Operations.Request.GetPostIndexByPageRequest): Promise<PersonalDomain.Application.Blogging.Models.PostIndexDTO> {
        return this.Post('/api/GetPostIndexByPage', jsonRequest);
    }    
    		
}
