//Generated by Flashman\James Chadwick at 11/3/2015 12:36 AM

declare module PersonalDomain.Application.Operations.Request {
	interface ByIdRequest {
		Id: number;
	}
	interface NullRequest {
	}
	interface GetPostDetailBySlugRequest {
		Slug: string;
	}
	interface GetPostSummariesByPageRequest {
		PageId: number;
		PageSize: number;
	}
}
declare module PersonalDomain.Application.Operations.Response {
	interface OperationResponse {
		IsSuccess: boolean;
	}
}
declare module PersonalDomain.Application.Blogging.Models {
	interface PostDetailDTO {
		Id: number;
		Title: string;
		Subtitle: string;
		Slug: string;
		Content: string;
		Comments: PersonalDomain.Application.Blogging.Models.CommentDTO[];
	}
	interface CommentDTO {
		Id: number;
		PostId: number;
		UserId: number;
		UserName: number;
		Content: string;
	}
	interface PostSummaryDTO {
		Id: number;
		Title: string;
		Subtitle: string;
		Slug: string;
		PostedDate: string;
		Author: string;
	}
	interface AuthorDTO {
		FullName: string;
		Tagline: string;
		Bio: string;
	}
	interface PostIndexDTO {
		PostSummaries: PersonalDomain.Application.Blogging.Models.PostSummaryDTO[];
		PostSummaryCount: number;
	}
}
