//Generated by Flashman\James Chadwick at 9/27/2015 12:47 AM

import {HttpClient} from 'aurelia-http-client';

export class BlogService {
    private _baseUrl: string = "http://blog.jamespchadwick.com";

    static inject = [HttpClient];
    constructor(private _httpClient: HttpClient) {
        _httpClient.configure(hc => hc.withHeader("Content-Type", "application/json;charset=UTF-8"));
    }

    public SaveComment: (jsonRequest: PersonalDomain.Application.Blogging.Models.CommentDTO) => Promise<PersonalDomain.Application.Operations.Response.OperationResponse> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/SaveComment', jsonRequest).then((httpResponse) => {
            return JSON.parse(httpResponse.response);
        });
    }    

    public SavePost: (jsonRequest: PersonalDomain.Application.Blogging.Models.PostDTO) => Promise<PersonalDomain.Application.Operations.Response.OperationResponse> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/SavePost', jsonRequest).then((httpResponse) => {
            return JSON.parse(httpResponse.response);
        });
    }    

    public GetAuthorById: (jsonRequest: PersonalDomain.Application.Operations.Request.ByIdRequest) => Promise<PersonalDomain.Application.Blogging.Models.AuthorDTO> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/GetAuthorById', jsonRequest).then((httpResponse) => {
            return JSON.parse(httpResponse.response);
        });
    }    

    public GetPostDetailBySlug: (jsonRequest: PersonalDomain.Application.Operations.Request.GetPostDetailBySlugRequest) => Promise<PersonalDomain.Application.Blogging.Models.PostDTO> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/GetPostDetailBySlug', jsonRequest).then((httpResponse) => {
            return JSON.parse(httpResponse.response);
        });
    }    

    public GetPostIndexByPage: (jsonRequest: PersonalDomain.Application.Operations.Request.GetPostIndexByPageRequest) => Promise<PersonalDomain.Application.Blogging.Models.PostIndexDTO> = (jsonRequest) => {
        return this._httpClient.post(this._baseUrl + '/api/GetPostIndexByPage', jsonRequest).then((httpResponse) => {
            return JSON.parse(httpResponse.response);
        });
    }    
		
}
