//Generated by Flashman\James Chadwick at 9/26/2015 12:59 AM

declare module AuthenticationAPI.Application.Owin.Operations.Request {
	interface ByIdRequest {
		Id: number;
	}
	interface GetBearerTokenRequest {
		Provider: string;
		ExternalAccessToken: string;
	}
	interface GetExternalLoginRequest {
		Provider: string;
		ClientId: string;
		RedirectPath: string;
	}
	interface GetTokenRequest {
		UserName: string;
		Password: string;
	}	
	interface NullRequest {
	}
}
declare module AuthenticationAPI.Application.Owin.Operations.Response {
	interface OperationResponse {
		IsSuccess: boolean;
	}
	interface RegisterExternalUserResponse {
		IsSuccess: boolean;
		BearerToken: AuthenticationAPI.Application.Models.BearerTokenDTO;
	}
	interface ExternalLoginResponse {
		StatusCode: System.Net.HttpStatusCode;
	}
}
declare module AuthenticationAPI.Application.Models {
	interface RegisterExternalUserDTO {
		UserName: string;
		Provider: string;
		Key: string;
		ExternalAccessToken: string;
	}
	interface BearerTokenDTO {
		Subject: string;
		Token: string;
		Type: string;
		ExpiresIn: string;
		Issued: string;
		Expires: string;
	}
	interface RegisterUserDTO {
		UserName: string;
		Password: string;
	}
	interface RefreshTokenDTO {
		Id: number;
		Issued: string;
		Expires: string;
		Hash: string;
	}
}
