using System;
using System.IO;
using System.Reflection;
using Tools.TypescriptGenerator.Configuration;

namespace Tools.TypescriptGenerator.Generators
{
    public abstract class TypescriptGeneratorBase
    {
        protected virtual String GeneratedBy
        {
            get
            {
                var currentUser = System.Security.Principal.WindowsIdentity.GetCurrent();
                var currentUserName = (currentUser == null) ? "Anonymous" : currentUser.Name;
                return "//Generated by " + currentUserName + " at " + DateTime.Now.ToShortDateString() + " " + DateTime.Now.ToShortTimeString();
            }
        }
        protected abstract Func<Type, Boolean> ProjectedTypeSelector { get; }

        public abstract void GenerateTypescript(Assembly source, Options options);
        protected virtual void WriteOutput(String path, String content)
        {
            File.WriteAllText(path, GeneratedBy + "\r\n" + content);
        }
    }
}
